import { Player, Match, Tournament } from './types';

export const MOCK_PLAYERS: Player[] = [
  { id: 1, name: 'Dick Jaspers', country: 'Netherlands', ranking: 1 },
  { id: 2, name: 'Torbjörn Blomdahl', country: 'Sweden', ranking: 2 },
  { id: 3, name: 'Marco Zanetti', country: 'Italy', ranking: 3 },
  { id: 4, name: 'Eddy Merckx', country: 'Belgium', ranking: 4 },
  { id: 5, name: 'Dani Sánchez', country: 'Spain', ranking: 5 },
  { id: 6, name: 'Quyet Chien Tran', country: 'Vietnam', ranking: 6 },
  { id: 7, name: 'Sameh Sidhom', country: 'Egypt', ranking: 7 },
  { id: 8, name: 'Tayfun Taşdemir', country: 'Turkey', ranking: 8 },
  { id: 9, name: 'Haeng Jik Kim', country: 'South Korea', ranking: 9 },
  { id: 10, name: 'Myung Woo Cho', country: 'South Korea', ranking: 10 },
  { id: 11, name: 'Semih Saygıner', country: 'Turkey', ranking: 11 },
  { id: 12, name: 'Jérémy Bury', country: 'France', ranking: 12 },
  { id: 13, name: 'Martin Horn', country: 'Germany', ranking: 13 },
  { id: 14, name: 'Jung Han Heo', country: 'South Korea', ranking: 14 },
  { id: 15, name: 'Nikos Polychronopoulos', country: 'Greece', ranking: 15 },
  { id: 16, name: 'Ruben Legazpi', country: 'Spain', ranking: 16 },
];

export const MOCK_MATCHES: Match[] = [
  {
    id: 101,
    tournamentId: 1,
    player1Id: 1,
    player2Id: 2,
    player1Score: 40,
    player2Score: 32,
    innings: 18,
    status: 'completed',
    startTime: '2024-05-20T10:00:00Z',
    tableNumber: 1,
    targetPoints: 40,
    highRun1: 12,
    highRun2: 7,
  },
  {
    id: 102,
    tournamentId: 1,
    player1Id: 3,
    player2Id: 4,
    player1Score: 40,
    player2Score: 38,
    innings: 22,
    status: 'completed',
    startTime: '2024-05-20T10:00:00Z',
    tableNumber: 2,
    targetPoints: 40,
    highRun1: 9,
    highRun2: 11,
  },
  {
    id: 103,
    tournamentId: 1,
    player1Id: 5,
    player2Id: 6,
    player1Score: 40,
    player2Score: 25,
    innings: 15,
    status: 'completed',
    startTime: '2024-05-20T10:00:00Z',
    tableNumber: 3,
    targetPoints: 40,
    highRun1: 14,
    highRun2: 6,
  },
  {
    id: 104,
    tournamentId: 1,
    player1Id: 7,
    player2Id: 8,
    player1Score: 40,
    player2Score: 39,
    innings: 28,
    status: 'completed',
    startTime: '2024-05-20T10:00:00Z',
    tableNumber: 4,
    targetPoints: 40,
    highRun1: 8,
    highRun2: 8,
  },
  {
    id: 105,
    tournamentId: 1,
    player1Id: 9,
    player2Id: 10,
    player1Score: 22,
    player2Score: 28,
    innings: 14,
    status: 'live',
    startTime: '2024-05-20T12:00:00Z',
    tableNumber: 1,
    targetPoints: 40,
    highRun1: 6,
    highRun2: 9,
  },
  {
    id: 106,
    tournamentId: 1,
    player1Id: 11,
    player2Id: 12,
    player1Score: 15,
    player2Score: 12,
    innings: 8,
    status: 'live',
    startTime: '2024-05-20T12:00:00Z',
    tableNumber: 2,
    targetPoints: 40,
    highRun1: 5,
    highRun2: 4,
  },
  {
    id: 107,
    tournamentId: 1,
    player1Id: 13,
    player2Id: 14,
    player1Score: 0,
    player2Score: 0,
    innings: 0,
    status: 'upcoming',
    startTime: '2024-05-20T14:00:00Z',
    tableNumber: 3,
    targetPoints: 40,
    highRun1: 0,
    highRun2: 0,
  },
  {
    id: 108,
    tournamentId: 1,
    player1Id: 15,
    player2Id: 16,
    player1Score: 0,
    player2Score: 0,
    innings: 0,
    status: 'upcoming',
    startTime: '2024-05-20T14:00:00Z',
    tableNumber: 4,
    targetPoints: 40,
    highRun1: 0,
    highRun2: 0,
  },
];

export const MOCK_TOURNAMENTS: Tournament[] = [
  {
    id: 1,
    name: 'Seoul World Cup 2024',
    location: 'Seoul, South Korea',
    type: 'knockout',
    startDate: '2024-05-01',
    endDate: '2024-05-07',
    targetPoints: 40,
    inningsLimit: 0,
    players: MOCK_PLAYERS,
    matches: MOCK_MATCHES,
  },
  {
    id: 2,
    name: 'European Championship 2024',
    location: 'Antalya, Turkey',
    type: 'round-robin',
    startDate: '2024-06-15',
    endDate: '2024-06-22',
    targetPoints: 40,
    inningsLimit: 50,
    players: MOCK_PLAYERS.slice(0, 8),
    matches: [],
  }
];
